# Generated by Django 5.2.8 on 2025-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Robot A', max_length=128)),
                ('addr', models.CharField(blank=True, default='', max_length=256)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('cleaning_progress', models.FloatField(default=0)),
                ('floor', models.CharField(default='1st', max_length=16)),
                ('status_text', models.CharField(default='Resting', max_length=64)),
                ('water_level', models.IntegerField(default=50)),
                ('battery', models.IntegerField(default=85)),
                ('fps', models.IntegerField(default=30)),
            ],
        ),
    ]
